version: 0.0
os: linux
files:
  - source: /target/springpoc-1.0.0-SNAPSHOT.war
    destination: /tmp/codedeploy-deployment-staging-area/
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/write_codedeploy_config.sh
    - location: scripts/start_server
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/basic_health_check.sh
    
