#!/bin/bash

echo " Starting Start Script"

set -e

CATALINA_HOME='/var/lib/tomcat8'
SERVER_HTTP_PORT='80'

docker login -u $dockerhubUser -p $dockerhubPassword

docker push trinitytg/springpoc:latest

docker run -d -it --rm -p 8888:8080 trinitytg/springpoc

docker logout

echo " End Start Script"
